### ISSUE TITLE
pinskylab_methods/genomics/analysis folder broken link

### ISSUE THREAD

**Issue by jahoey** [mpinsky/pinskylab_methods#16]
Hi Michelle - I can't seem to access the 'analysis folder' directory that has protocols and scripts

**Comment by mstuart1** [comment]
I moved my scripts and protocols into the genomics repository because that is where I was using them most.  What are you looking for?  I can help you find an old version or update you on our current methods.

**Comment by mstuart1** [comment]
Here is a link to the current version of everything that was in the analysis folder -[ this document is a navigational tool to reach each of the protocols.](https://github.com/pinskylab/genomics/blob/master/README.md)
