### ISSUE TITLE
Guide to using Amarel cluster

### ISSUE THREAD

**Issue by mpinsky** [mpinsky/pinskylab_methods#3]
To be written by Jennifer Hoey, summer 2017

**Comment by jahoey** [comment]
Uploaded Amarel guide. See commit 510fea5.

**Comment by mpinsky** [comment]
@jahoey This somehow isn't appearing as a commit in the repository. Trying syncing or pulling again?

Also check line endings. I think that's why it's not formatting well.

**Comment by jahoey** [comment]
@mpinsky I'm on a branch of pinsky_labmethods, so I just created a pull request to merge with the master. I also figured out what the issue was with the formatting - I needed a space to get the markdown formatting to apply.
